import{a as B,S as w,i as l}from"./assets/vendor-Rdv7LHNr.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const v="46842885-9f0c2ceed82c15a306e254aa9",I="https://pixabay.com/api/",b=15;async function P(t,o=1){try{const a=await B.get(I,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:b}});return{images:a.data.hits,totalHits:a.data.totalHits}}catch(a){throw console.error("Error fetching images:",a),a}}let c;function H(t){const o=document.getElementById("gallery"),a=t.map(({webformatURL:i,largeImageURL:e,tags:r,likes:n,views:h,comments:E,downloads:L})=>`
    <li class="item gallery-item">
        <a href="${e}" class="image-card">
            <img src="${i}" alt="${r}" loading="lazy" class="gallery-image"/>
            <div class="image-info">
                <span>❤️ ${n}</span>
                <span>👁️ ${h}</span>
                <span>💬 ${E}</span>
                <span>⬇️ ${L}</span>
            </div>
        </a>
        </li>
    `).join("");o.insertAdjacentHTML("beforeend",a),c?c.refresh():c=new w(".gallery a",{captionsData:"alt",captionDelay:250})}function S(){document.getElementById("loader").classList.remove("hidden")}function $(){document.getElementById("loader").classList.add("hidden")}function m(t){const o=document.getElementById("load-more");o.style.display=t?"block":"none"}const A=document.getElementById("search-form"),g=document.getElementById("search-input"),f=document.getElementById("gallery"),y=document.getElementById("load-more");let d="",s=1,u=0;A.addEventListener("submit",async t=>{if(t.preventDefault(),d=g.value.trim(),!d){l.error({title:"Error",message:"Please enter a search term."});return}s=1,f.innerHTML="",y.style.display="none",await p()});y.addEventListener("click",p);async function p(){S();try{const{images:t,totalHits:o}=await P(d,s);t.length===0&&s===1?l.warning({message:"Sorry, there are no images matching your search query. Please try again!"}):(H(t),u=o,s*15>=u?(m(!1),l.info({message:"We're sorry, but you've reached the end of search results."})):(m(!0),s+=1),M())}catch{l.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{$(),g.value=""}}function M(){const{height:t}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
